# Rustfmt configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
use_small_heuristics = "Default"
fn_single_line = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true